name 'zennoc-squid3'
version '0.0.1'

author 'Nathan Flynn'
license 'Apache2'
project_page 'http://www.zen.co.uk'
source 'https://github.com/zennoc/puppet-squid3'
summary 'Puppet module for squid3'
description 'This module installs and manages squid3. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
